"""
Puzzle isles — failable, time-limited brain challenges.

Five interactive/generated kinds (client never receives fields in "secret"):

  · tetromino  Talos-Principle-style sigil fill: drag the given pieces to
               tile the region exactly (a quick 4×4 in STRIKE combat, the full
               6×6 on isles and in MAGIC). NO rotation — each piece comes in the
               orientation it must be placed. Generated by tiling the region
               first, so always solvable; placed pieces can be dragged to move.
  · nonogram   5×5 picross against a 30s clock: paint cells to satisfy
               row/column clues. Just TWO cells come pre-filled ("given"
               cells, locked in the client). Any grid matching the clues counts.
  · simon      memory: watch a flashed sequence on a 3×3 pad, then reproduce
               it (4 tones in a STRIKE-vs-pack fight, 6 elsewhere).
  · visual_memory  Human-Benchmark recall: a 6×6 board flashes a set of tiles;
               memorise them, then click them all back. Three misses (lives)
               ends it. The flashed set is public (the client lights it), like
               simon's sequence — the checker just verifies the picks.
  · anagram    unscramble a themed word (typed answer).
  · ravens     Raven's-matrix: 3×3 glyph grid follows hidden row/col rules;
               pick the missing ninth tile.
  · sequence   "The Fates' Thread": a number sequence from a random rule
               (arith/geo/fib/squares/primes/triangular/cubes) — type the next
               term. The answer rides in "secret".
  · lights_out "The Gorgon's Gaze": a 4×4 grid; tapping a cell toggles it and
               its orthogonal neighbours — extinguish every light. Scrambled
               from all-off, so always solvable by replaying taps.
  · sliding    "The Shifting Mosaic": a 3×3 sliding-tile puzzle (0 = blank),
               scrambled from the solved goal with legal moves (always
               solvable); restore the goal order.

Plus "riddle" — a typed-answer brain teaser (like anagram, an INTERACTIVE
minigame): the player reads a themed riddle and types the answer against a 30s
clock. The answer rides in "secret"; the checker normalizes case, whitespace,
leading articles and punctuation, and accepts spelling variants. Content lives
in riddles_typed.RIDDLES (50 riddles across 5 THALASSA themes).
"""
from __future__ import annotations

import random

import riddles_typed
import tetromino6

# time limit (seconds) per kind — the server enforces these.
# Simon has NO clock: one wrong tap is the failure, not the seconds.
# 20s across the board — nonogram (picross) gets 30 for its fiddlier grid;
# simon stays untimed (a wrong note, not the clock, is its failure).
TIME_LIMITS = {"riddle": 27.5, "tetromino": 40, "nonogram": 49.375,
               "simon": None, "anagram": 27.5, "ravens": 22.5,
               "sequence": 27.5, "lights_out": 27.5, "sliding": 70,
               "memory": None,           # memory (like simon) has no clock
               "visual_memory": 30}      # a clock backstop; 3 misses is the real end

INTERACTIVE = ("tetromino", "nonogram", "simon", "anagram", "ravens", "riddle",
               "sequence", "lights_out", "sliding", "memory", "visual_memory")

# ── typed-answer riddles — content + normalization live in riddles_typed ─────
RIDDLES = riddles_typed.RIDDLES

# ── anagram wordlist (mythology / seafaring / worldly — 6-9 letters) ─────────
WORDS = [
    "ODYSSEY", "TRIREME", "ORACLE", "OLYMPUS", "LABYRINTH", "MINOTAUR",
    "PEGASUS", "TITANS", "AEGEAN", "HELMSMAN", "COMPASS", "LANTERN",
    "HARBOR", "ANCHOR", "VOYAGE", "ISLAND", "TEMPEST", "SIRENS",
    "GOLDEN", "FLEECE", "ARGONAUT", "CENTAUR", "GRIFFIN", "PHOENIX",
    "MARBLE", "COLUMN", "TEMPLE", "SCROLLS", "RIDDLES", "SPHINX",
    "CYCLOPS", "HYDRA", "KRAKEN", "POSEIDON", "ATHENA", "HERMES",
    "APOLLO", "ARTEMIS", "DOLPHIN", "OCTOPUS", "SEAWEED", "CORAL",
    "PIRATE", "PLUNDER", "TREASURE", "RELIC", "AMPHORA", "CHARIOT",
    "JAVELIN", "STADIUM", "LAUREL", "OLIVES", "GRAPES", "HONEY",
    "THUNDER", "TRIDENT", "SANDALS", "HELMET", "GALLEY", "RUDDER",
]
_WORD_SET = set(WORDS)


# ── tetromino sigil fill (Talos-Principle style) ─────────────────────────────
TETROMINOES = {
    "I": [(0, 0), (1, 0), (2, 0), (3, 0)],
    "O": [(0, 0), (1, 0), (0, 1), (1, 1)],
    "T": [(0, 0), (1, 0), (2, 0), (1, 1)],
    "S": [(1, 0), (2, 0), (0, 1), (1, 1)],
    "Z": [(0, 0), (1, 0), (1, 1), (2, 1)],
    "L": [(0, 0), (0, 1), (0, 2), (1, 2)],
    "J": [(1, 0), (1, 1), (1, 2), (0, 2)],
}


def _normalize(cells) -> tuple:
    xs = min(x for x, y in cells)
    ys = min(y for x, y in cells)
    return tuple(sorted((x - xs, y - ys) for x, y in cells))


def _rotations(shape) -> list[tuple]:
    out, cur = [], list(shape)
    for _ in range(4):
        cur = [(y, -x) for x, y in cur]
        n = _normalize(cur)
        if n not in out:
            out.append(n)
    return out

ROTATIONS = {name: _rotations(shape) for name, shape in TETROMINOES.items()}


def gen_tetromino(rng: random.Random, w: int = 4, h: int = 4) -> dict:
    """Tile the region (rotations allowed while GENERATING), then hand each
    piece to the player in exactly the orientation it was placed."""
    grid = [-1] * (w * h)
    forms: list[tuple] = []                 # normalized form of each placed piece

    def fit(form, x0, y0):
        cells = []
        for dx, dy in form:
            x, y = x0 + dx, y0 + dy
            if not (0 <= x < w and 0 <= y < h) or grid[y * w + x] != -1:
                return None
            cells.append((x, y))
        return cells

    def solve() -> bool:
        try:
            i = grid.index(-1)
        except ValueError:
            return True
        y0, x0 = divmod(i, w)
        names = list(ROTATIONS)
        rng.shuffle(names)
        for name in names:
            for form in ROTATIONS[name]:
                for ax, ay in form:
                    cells = fit([(dx - ax, dy - ay) for dx, dy in form], x0, y0)
                    if cells:
                        idx = len(forms)
                        for x, y in cells:
                            grid[y * w + x] = idx
                        forms.append(_normalize(cells))
                        if solve():
                            return True
                        for x, y in cells:
                            grid[y * w + x] = -1
                        forms.pop()
        return False

    solve()
    order = list(range(len(forms)))
    rng.shuffle(order)
    pieces = [[list(c) for c in forms[i]] for i in order]
    return {"w": w, "h": h, "pieces": pieces, "secret": {}}


def check_tetromino(data: dict, assignment) -> bool:
    w, h, pieces = data["w"], data["h"], data["pieces"]
    if not isinstance(assignment, list) or len(assignment) != w * h:
        return False
    groups: dict[int, list] = {}
    for i, v in enumerate(assignment):
        if not isinstance(v, int) or not 0 <= v < len(pieces):
            return False
        groups.setdefault(v, []).append((i % w, i // w))
    if len(groups) != len(pieces):
        return False
    for idx, cells in groups.items():
        want = tuple(sorted(tuple(c) for c in pieces[idx]))
        if len(cells) != 4 or _normalize(cells) != want:
            return False
    return True


# ── nonogram (picross 5×5) ───────────────────────────────────────────────────
def _clues(line) -> list[int]:
    out, run = [], 0
    for v in line:
        if v:
            run += 1
        elif run:
            out.append(run)
            run = 0
    if run:
        out.append(run)
    return out or [0]


def gen_nonogram(rng: random.Random, n: int = 5, givens: int = 2) -> dict:
    while True:
        grid = [1 if rng.random() < 0.55 else 0 for _ in range(n * n)]
        filled = sum(grid)
        if n + 2 <= filled <= n * n - 3:            # not trivial, not full
            break
    rows = [_clues(grid[r * n:(r + 1) * n]) for r in range(n)]
    cols = [_clues(grid[c::n]) for c in range(n)]
    # `givens` cells come pre-painted — a toe-hold. The puzzle isles and the
    # MAGIC picross set this differently (STRIKE gets 5, MAGIC gets 0).
    filled_idx = [i for i, v in enumerate(grid) if v]
    given = sorted(rng.sample(filled_idx, min(max(0, givens), len(filled_idx))))
    return {"n": n, "rows": rows, "cols": cols, "given": given, "secret": {}}


def check_nonogram(data: dict, grid) -> bool:
    n = data["n"]
    if not isinstance(grid, list) or len(grid) != n * n:
        return False
    if any(v not in (0, 1) for v in grid):
        return False
    rows = [_clues(grid[r * n:(r + 1) * n]) for r in range(n)]
    cols = [_clues(grid[c::n]) for c in range(n)]
    return rows == data["rows"] and cols == data["cols"]


# ── simon (memory sequence, starts at 6) ─────────────────────────────────────
def gen_simon(rng: random.Random, length: int = 6) -> dict:
    seq = []
    for _ in range(length):
        nxt = rng.randrange(9)
        while seq and nxt == seq[-1]:               # no immediate repeats
            nxt = rng.randrange(9)
        seq.append(nxt)
    # the sequence must be public — the client has to flash it
    return {"pad": 9, "seq": seq, "secret": {}}


def check_simon(data: dict, taps) -> bool:
    return isinstance(taps, list) and taps == data["seq"]


# ── memory (simon's little sibling: a 2×2 pad, only 4 to remember) ───────────
def gen_memory(rng: random.Random, length: int = 4) -> dict:
    seq = []
    for _ in range(length):
        nxt = rng.randrange(4)
        while seq and nxt == seq[-1]:               # no immediate repeats
            nxt = rng.randrange(4)
        seq.append(nxt)
    return {"pad": 4, "seq": seq, "secret": {}}     # pad 4 → a 2×2 board


# ── visual memory (Human Benchmark): flash tiles, then click them back ───────
def gen_visual_memory(rng: random.Random, n: int = 6,
                      lit: int | None = None) -> dict:
    """An n×n board briefly flashes `lit` tiles; memorise them, then click them
    all back. THREE misses (lives) and it's lost. The flashed set is PUBLIC —
    the client has to light it — exactly like simon's sequence; the checker just
    verifies the picks match it. One clean round wins the trial. About a THIRD of
    the board lights (the Human-Benchmark density): ~8 tiles on a 5×5, 11 on a
    6×6, 15 on a 7×7."""
    if lit is None:
        lit = max(4, round(n * n * 0.3))
    lit = min(lit, n * n)
    cells = sorted(rng.sample(range(n * n), lit))
    return {"n": n, "flash": cells, "lives": 3, "secret": {}}


def check_visual_memory(data: dict, picks) -> bool:
    """Pass only if EVERY flashed tile was found and no stray tile submitted —
    the client sends the set it uncovered when the board is cleared."""
    return isinstance(picks, list) and sorted(set(picks)) == data["flash"]


# ── anagram unscramble ───────────────────────────────────────────────────────
def gen_anagram(rng: random.Random) -> dict:
    word = rng.choice(WORDS)
    letters = list(word)
    for _ in range(20):
        rng.shuffle(letters)
        if "".join(letters) != word:
            break
    return {"letters": "".join(letters), "length": len(word),
            "secret": {"word": word}}


def check_anagram(data: dict, guess) -> bool:
    if not isinstance(guess, str):
        return False
    guess = guess.strip().upper()
    word = data["secret"]["word"]
    if guess == word:
        return True
    # any real word from our list using exactly these letters also counts
    return sorted(guess) == sorted(word) and guess in _WORD_SET


# ── raven's matrix ───────────────────────────────────────────────────────────
_SHAPES = ["circle", "square", "triangle", "diamond"]
_FILLS = ["empty", "half", "full"]


def _rule(rng: random.Random, values: list):
    """Returns f(row, col) -> value; one of three systematic rules."""
    vals = values[:]
    rng.shuffle(vals)
    vals = vals[:3]
    mode = rng.choice(["row", "col", "latin"])
    if mode == "row":
        return lambda r, c: vals[r]
    if mode == "col":
        return lambda r, c: vals[c]
    return lambda r, c: vals[(r + c) % 3]


def gen_ravens(rng: random.Random) -> dict:
    shape_of = _rule(rng, _SHAPES)
    count_of = _rule(rng, [1, 2, 3])
    fill_of = _rule(rng, _FILLS)
    glyph = lambda r, c: {"shape": shape_of(r, c), "count": count_of(r, c),
                          "fill": fill_of(r, c)}
    grid = [glyph(r, c) for r in range(3) for c in range(3)]
    answer = grid[8]
    shown = grid[:8]

    def mutate(g):
        m = dict(g)
        attr = rng.choice(["shape", "count", "fill"])
        if attr == "shape":
            m["shape"] = rng.choice([s for s in _SHAPES if s != g["shape"]])
        elif attr == "count":
            m["count"] = rng.choice([n for n in (1, 2, 3, 4) if n != g["count"]])
        else:
            m["fill"] = rng.choice([f for f in _FILLS if f != g["fill"]])
        return m

    options = [answer]
    guard = 0
    while len(options) < 4 and guard < 200:
        guard += 1
        cand = mutate(answer)
        if rng.random() < 0.4:
            cand = mutate(cand)
        if cand not in options:
            options.append(cand)
    rng.shuffle(options)
    return {"grid": shown, "options": options,
            "secret": {"correct": options.index(answer)}}


def check_ravens(data: dict, idx) -> bool:
    return isinstance(idx, int) and idx == data["secret"]["correct"]


# ── riddle (typed answer) ────────────────────────────────────────────────────
def check_riddle(data: dict, guess) -> bool:
    if not isinstance(guess, str):
        return False
    return riddles_typed.check_riddle(data["secret"], guess)


# ── sequence: "The Fates' Thread" (type the next term) ───────────────────────
def gen_sequence(rng: random.Random) -> dict:
    """A number sequence from a random rule; the next term rides in secret."""
    fam = rng.choice(["arith", "geo", "fib", "squares",
                      "primes", "triangular", "cubes"])
    if fam == "arith":
        start, step = rng.randint(1, 9), rng.randint(2, 9)
        terms = [start + step * i for i in range(5)]
        answer = start + step * 5
    elif fam == "geo":
        start, ratio = rng.randint(1, 4), rng.randint(2, 3)
        terms = [start * ratio ** i for i in range(4)]
        answer = start * ratio ** 4
    elif fam == "fib":
        seq = [rng.randint(1, 3), rng.randint(2, 4)]
        while len(seq) < 6:
            seq.append(seq[-1] + seq[-2])
        terms, answer = seq[:5], seq[5]
    elif fam == "squares":
        off = rng.randint(0, 3)
        terms = [(i + 1 + off) ** 2 for i in range(5)]
        answer = (6 + off) ** 2
    elif fam == "primes":
        primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41]
        s = rng.randint(0, 4)
        terms, answer = primes[s:s + 5], primes[s + 5]
    elif fam == "triangular":
        off = rng.randint(0, 4)
        terms = [(k * (k + 1)) // 2 for k in range(1 + off, 6 + off)]
        answer = ((6 + off) * (7 + off)) // 2
    else:                                                   # cubes
        off = rng.randint(0, 2)
        terms = [(i + 1 + off) ** 3 for i in range(4)]
        answer = (5 + off) ** 3
    return {"terms": terms, "secret": {"answer": answer}}


def check_sequence(data: dict, guess) -> bool:
    try:
        return int(str(guess).strip()) == int(data["secret"]["answer"])
    except (ValueError, TypeError):
        return False


# ── lights out: "The Gorgon's Gaze" (extinguish every light) ─────────────────
def _lights_toggle(board, n, r, c):
    for rr, cc in ((r, c), (r - 1, c), (r + 1, c), (r, c - 1), (r, c + 1)):
        if 0 <= rr < n and 0 <= cc < n:
            board[rr][cc] ^= 1


def gen_lights_out(rng: random.Random, n: int = 4, depth: int = 5) -> dict:
    """Scramble from an all-off board with `depth` taps — always solvable by
    replaying those taps. Reroll if the scramble lands back on all-off."""
    while True:
        board = [[0] * n for _ in range(n)]
        for _ in range(depth):
            _lights_toggle(board, n, rng.randrange(n), rng.randrange(n))
        if any(v for row in board for v in row):
            return {"n": n, "board": board, "secret": {}}


def check_lights_out(data: dict, taps) -> bool:
    n = data["n"]
    if not isinstance(taps, list):
        return False
    board = [row[:] for row in data["board"]]
    for tap in taps:
        if not (isinstance(tap, (list, tuple)) and len(tap) == 2):
            return False
        r, c = tap
        if not (isinstance(r, int) and isinstance(c, int)
                and 0 <= r < n and 0 <= c < n):
            return False
        _lights_toggle(board, n, r, c)
    return all(v == 0 for row in board for v in row)


# ── sliding tile: "The Shifting Mosaic" (3×3, 0 = blank) ─────────────────────
_SLIDE_GOAL = [1, 2, 3, 4, 5, 6, 7, 8, 0]


def _slide_neighbors(board):
    z = board.index(0)
    r, c = divmod(z, 3)
    out = []
    for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
        nr, nc = r + dr, c + dc
        if 0 <= nr < 3 and 0 <= nc < 3:
            out.append(nr * 3 + nc)
    return out


def gen_sliding(rng: random.Random, scramble: int = 25) -> dict:
    """Only ever scramble the solved goal with legal blank-swaps, so the board
    is always solvable. Reroll if the walk lands back on the goal."""
    while True:
        board = list(_SLIDE_GOAL)
        last = None
        for _ in range(scramble):
            z = board.index(0)
            nbrs = _slide_neighbors(board)
            opts = [p for p in nbrs if p != last] or nbrs
            pos = rng.choice(opts)
            last = z
            board[z], board[pos] = board[pos], board[z]
        if board != _SLIDE_GOAL:
            return {"board": board, "goal": list(_SLIDE_GOAL), "secret": {}}


def check_sliding(data: dict, board) -> bool:
    return isinstance(board, list) and board == data["goal"]


# ── dealing & checking ───────────────────────────────────────────────────────
_WEIGHTS = [("tetromino", 3), ("nonogram", 3), ("simon", 3),
            ("anagram", 3), ("ravens", 3), ("riddle", 1),
            ("sequence", 3), ("lights_out", 3), ("sliding", 3),
            ("visual_memory", 3)]
_GENERATORS = {"tetromino": gen_tetromino, "nonogram": gen_nonogram,
               "simon": gen_simon, "anagram": gen_anagram, "ravens": gen_ravens,
               "sequence": gen_sequence, "lights_out": gen_lights_out,
               "sliding": gen_sliding, "memory": gen_memory,
               "visual_memory": gen_visual_memory}
_CHECKERS = {"tetromino": check_tetromino, "nonogram": check_nonogram,
             "simon": check_simon, "anagram": check_anagram, "ravens": check_ravens,
             "riddle": check_riddle, "sequence": check_sequence,
             "lights_out": check_lights_out, "sliding": check_sliding,
             "memory": check_simon,     # memory reuses simon's exact-sequence check
             "visual_memory": check_visual_memory}

# The Sigil of the Isle is now a 6×6 board (9 tetrominoes, NO rotation), dealt
# from a bank of 20 fixed solvable instances. check_tetromino is size-agnostic
# and unchanged. Piece/secret format matches the game's exactly.
_GENERATORS["tetromino"] = lambda rng: dict(rng.choice(tetromino6.BANK)["public"])


def deal(rng: random.Random, used_riddles: set[int]) -> dict:
    pool = [k for k, wt in _WEIGHTS for _ in range(wt)]
    kind = rng.choice(pool)
    if kind == "riddle":
        fresh = [i for i in range(len(RIDDLES)) if i not in used_riddles]
        if not fresh:
            kind = rng.choice(list(_GENERATORS))
        else:
            idx = rng.choice(fresh)
            used_riddles.add(idx)
            r = RIDDLES[idx]
            # typed-answer minigame: text is public, answer stays in secret
            return {"kind": "riddle", "limit": TIME_LIMITS["riddle"],
                    "text": r["prompt"], "category": r["category"],
                    "secret": {"answer": r["answer"], "accept": r["accept"]}}
    data = _GENERATORS[kind](rng)
    data.update({"kind": kind, "limit": TIME_LIMITS[kind]})
    return data


def check(kind: str, data: dict, payload) -> bool:
    fn = _CHECKERS.get(kind)
    return bool(fn and fn(data, payload))


# ── special deals ─────────────────────────────────────────────────────────────
# Combat puzzles are TIERED by the stance you chose (STRIKE/GUARD → I, boss
# STRIKE → II, MAGIC → III), so a harder stance draws a harder trial. Anagrams
# and the tetromino sigil-fill are TOO SLOW for a fight and never appear here
# (they still turn up on the puzzle isles). Riddles belong to the Sphinx.
# Pool entries are TOKENS: bare kinds ("nonogram", "sliding"…) or sized tokens
# — vm5/vm6/vm7 (visual-memory board size), simon4/simon6 (echo length),
# tet4/tet6 (sigil board) — resolved in deal_battle. Same kind on the wire.
BATTLE_TIERS = {
    # STRIKE vs pack: the 4-tone echo (simon), the 5×5 board, a quick 4×4 sigil,
    # the Gorgon's Gaze, the Fates' Thread, a riddle, and a 5×5 picross with a
    # generous FIVE cells given (nono5) — the easy-stance picross
    1: ("simon4", "vm5", "tet4", "lights_out", "sequence", "riddle", "nono5"),
    # STRIKE vs boss: the 6-tone echo, the 5×5 board, the Shifting Mosaic, a
    # riddle, and the same 5-given picross
    2: ("simon6", "vm5", "sliding", "riddle", "nono5"),
    # MAGIC: the same 5×5 picross but with just TWO cells given (nono2), the
    # matrix, the full 6×6 sigil, the Shifting Mosaic, and the big 6×6 memory board
    3: ("nono2", "ravens", "tet6", "sliding", "vm6"),
}
BATTLE_KINDS = tuple(dict.fromkeys(k for ks in BATTLE_TIERS.values() for k in ks))


def deal_kind(rng: random.Random, kind: str) -> dict:
    """A fresh instance of one specific interactive puzzle kind."""
    data = _GENERATORS[kind](rng)
    data.update({"kind": kind, "limit": TIME_LIMITS[kind]})
    return data


def answer_text(kind: str, data: dict | None) -> str:
    """A short, human-readable form of the correct answer, for the on-screen
    'the answer was…' reveal on a failed puzzle. Empty for the grid puzzles
    (tetromino/nonogram/simon/lights-out/sliding) whose answer is a layout."""
    if not data:
        return ""
    s = data.get("secret", {}) or {}
    if kind == "anagram":
        return str(s.get("word", "")).upper()
    if kind in ("riddle", "sequence"):
        return str(s.get("answer", ""))
    return ""


def deal_battle(rng: random.Random, tier: int = 1,
                used_riddles: set[int] | None = None) -> dict:
    """A combat puzzle drawn from the pool for this battle tier (see
    BATTLE_TIERS). Sized tokens resolve here: vm<n> → an n×n memory board,
    simon<n> → an n-tone echo, tet<n> → an n×n sigil (4 procedural, 6 from the
    bank). Riddles come from the shared used-riddle set so a fight never repeats
    one; the slow anagram is still out of combat."""
    pool = BATTLE_TIERS.get(tier) or BATTLE_TIERS[2]
    tok = rng.choice(pool)
    if tok == "riddle":
        return deal_riddle(rng, set() if used_riddles is None else used_riddles)
    if tok.startswith("vm"):                        # vm5 / vm6 / vm7
        data = gen_visual_memory(rng, n=int(tok[2:]))
        data.update({"kind": "visual_memory", "limit": TIME_LIMITS["visual_memory"]})
        return data
    if tok.startswith("simon"):                     # simon4 / simon6
        data = gen_simon(rng, length=int(tok[5:]))
        data.update({"kind": "simon", "limit": TIME_LIMITS["simon"]})
        return data
    if tok.startswith("tet"):                       # tet4 / tet6
        n = int(tok[3:])
        if n >= 6:                                  # the full 6×6 board — 40s
            data = dict(rng.choice(tetromino6.BANK)["public"])
            limit = TIME_LIMITS["tetromino"]
        else:                                       # a quick STRIKE 4×4 — 15s
            data = gen_tetromino(rng, n, n)
            limit = 15
        data.update({"kind": "tetromino", "limit": limit})
        return data
    if tok.startswith("nono"):                      # nono5 (STRIKE) / nono0 (MAGIC)
        suffix = tok[4:]
        givens = int(suffix) if suffix.isdigit() else 2
        data = gen_nonogram(rng, givens=givens)
        data.update({"kind": "nonogram", "limit": TIME_LIMITS["nonogram"]})
        return data
    return deal_kind(rng, tok)


def deal_riddle(rng: random.Random, used_riddles: set[int]) -> dict:
    """A typed riddle (the Sphinx's toll). Reuses the game's used-riddle set;
    when the book runs dry it simply starts over."""
    fresh = [i for i in range(len(RIDDLES)) if i not in used_riddles]
    if not fresh:
        used_riddles.clear()
        fresh = list(range(len(RIDDLES)))
    idx = rng.choice(fresh)
    used_riddles.add(idx)
    r = RIDDLES[idx]
    return {"kind": "riddle", "limit": TIME_LIMITS["riddle"],
            "text": r["prompt"], "category": r["category"],
            "secret": {"answer": r["answer"], "accept": r["accept"]}}
