"""
Puzzle isles — failable, time-limited brain challenges.

Five kinds. Three are INTERACTIVE MINIGAMES, generated fresh every time and
validated server-side (the client never receives a solution):

  · sliding    3×3 eight-puzzle — scrambled by legal moves, so always solvable
  · lightsout  4×4 toggle grid — generated by pressing from solved, so always solvable
  · tetromino  fill a 4×5 region exactly with 5 tetromino pieces — generated by
               actually tiling the region first, so always solvable

Two are timed multiple-choice:

  · sequence   generated "what comes next?" number/letter patterns (infinite)
  · riddle     ★ PLACEHOLDER hand-written brain teasers — replace with your own.
               Good sources: Project Gutenberg (Sam Loyd's "Cyclopedia of
               Puzzles", Dudeney's "Amusements in Mathematics" — public domain),
               Martin Gardner / Raymond Smullyan collections, Puzzling
               StackExchange (CC BY-SA, keep attribution), MindYourDecisions,
               NPR Sunday Puzzle, Mensa/GCHQ puzzle books.

Riddle format: {"text": ..., "options": [4 strings], "correct": one of them}.
"""
from __future__ import annotations

import random

# time limit (seconds) per kind — the server enforces these
TIME_LIMITS = {"riddle": 60, "sequence": 60, "sliding": 75,
               "lightsout": 45, "tetromino": 100}

# ── canned riddles (PLACEHOLDERS — swap in your own set) ─────────────────────
RIDDLES: list[dict] = [
    {"text": "I am taken from a mine and shut in a wooden case, from which I am "
             "never released — yet almost everyone uses me. What am I?",
     "options": ["Pencil lead", "A diamond", "Coal", "A nail"],
     "correct": "Pencil lead"},
    {"text": "A farmer must ferry a wolf, a goat, and a cabbage across a river. The "
             "boat holds the farmer and one item. Unattended, wolf eats goat, goat "
             "eats cabbage. Minimum crossings?",
     "options": ["7", "5", "9", "11"], "correct": "7"},
    {"text": "Two guards, two doors: one door frees you, one dooms you; one guard "
             "always lies, one always tells the truth. One question to find freedom?",
     "options": [
         "Ask either: “Which door would the other guard call safe?” — take the opposite",
         "Ask either: “Are you the liar?” — trust whoever says no",
         "Ask either: “Which door is safe?” — take the door indicated",
         "No single question can settle it"],
     "correct": "Ask either: “Which door would the other guard call safe?” — take the opposite"},
    {"text": "A snail climbs a 10 m well: up 3 m by day, back 2 m by night. "
             "On which day does it get out?",
     "options": ["Day 8", "Day 10", "Day 7", "Day 9"], "correct": "Day 8"},
    {"text": "You overtake the runner in second place. What place are you in now?",
     "options": ["Second", "First", "Third", "Depends on the field"],
     "correct": "Second"},
    {"text": "A cube painted red is cut into 27 equal cubes. How many small cubes "
             "have exactly two painted faces?",
     "options": ["12", "8", "6", "9"], "correct": "12"},
    {"text": "Using 3, 3, 8, 8 each exactly once with + − × ÷ and parentheses, "
             "which expression makes 24?",
     "options": ["8 ÷ (3 − 8 ÷ 3)", "(8 + 8) × 3 ÷ 3", "3 × 8 + 3 − 8", "(3 + 3) × 8 ÷ 8"],
     "correct": "8 ÷ (3 − 8 ÷ 3)"},
    {"text": "What comes next: O, T, T, F, F, S, S, …?",
     "options": ["E", "N", "T", "O"], "correct": "E"},
]


# ── generated sequences (infinite multiple-choice) ───────────────────────────
def gen_sequence(rng: random.Random) -> dict:
    kind = rng.choice(["arith", "geom", "squares", "fib", "alt", "lookandsay", "letters"])
    if kind == "arith":
        a, d = rng.randint(2, 30), rng.choice([3, 4, 6, 7, 9, 11, 13])
        seq = [a + d * k for k in range(5)]
        nxt = a + d * 5
    elif kind == "geom":
        a, r = rng.randint(2, 6), rng.choice([2, 3])
        seq = [a * r**k for k in range(5)]
        nxt = a * r**5
    elif kind == "squares":
        off = rng.randint(-3, 3)
        start = rng.randint(2, 7)
        seq = [k * k + off for k in range(start, start + 5)]
        nxt = (start + 5) ** 2 + off
    elif kind == "fib":
        a, b = rng.randint(1, 5), rng.randint(2, 7)
        seq = [a, b]
        for _ in range(3):
            seq.append(seq[-1] + seq[-2])
        nxt = seq[-1] + seq[-2]
    elif kind == "alt":
        a, up, dn = rng.randint(10, 40), rng.randint(5, 12), rng.randint(1, 4)
        seq, cur = [], a
        for k in range(5):
            seq.append(cur)
            cur = cur + (up if k % 2 == 0 else -dn)
        nxt = cur
    elif kind == "lookandsay":
        seq_s = ["1"]
        for _ in range(4):
            s, out, i = seq_s[-1], "", 0
            while i < len(s):
                j = i
                while j < len(s) and s[j] == s[i]:
                    j += 1
                out += str(j - i) + s[i]
                i = j
            seq_s.append(out)
        s, out, i = seq_s[-1], "", 0
        while i < len(s):
            j = i
            while j < len(s) and s[j] == s[i]:
                j += 1
            out += str(j - i) + s[i]
            i = j
        text = "What comes next?  " + ", ".join(seq_s) + ", …"
        wrongs = {out[::-1], out[:-1] + "1", "1" + out[:-1]} - {out}
        options = [out] + list(wrongs)[:3]
        while len(options) < 4:
            options.append(out[:-1] + str(rng.randint(2, 9)))
        rng.shuffle(options)
        return {"text": text, "options": options, "correct": options.index(out)}
    else:  # letters — skip-count through the alphabet
        step = rng.randint(2, 4)
        start = rng.randint(0, 5)
        idxs = [start + step * k for k in range(5)]
        seq_l = [chr(ord("A") + i % 26) for i in idxs]
        nxt_l = chr(ord("A") + (start + step * 5) % 26)
        text = "What letter comes next?  " + ", ".join(seq_l) + ", …"
        wrongs = set()
        while len(wrongs) < 3:
            w = chr(ord("A") + rng.randint(0, 25))
            if w != nxt_l:
                wrongs.add(w)
        options = [nxt_l] + sorted(wrongs)
        rng.shuffle(options)
        return {"text": text, "options": options, "correct": options.index(nxt_l)}

    text = "What number comes next?  " + ", ".join(str(x) for x in seq) + ", …"
    deltas = sorted({abs(seq[-1] - seq[-2]), 1, 2, rng.randint(3, 9)})
    wrongs = []
    for d in deltas:
        for cand in (nxt + d, nxt - d):
            if cand != nxt and cand not in wrongs and cand > 0:
                wrongs.append(cand)
    rng.shuffle(wrongs)
    options = [str(nxt)] + [str(w) for w in wrongs[:3]]
    rng.shuffle(options)
    return {"text": text, "options": options, "correct": options.index(str(nxt))}


# ── sliding 8-puzzle ─────────────────────────────────────────────────────────
def gen_sliding(rng: random.Random, scramble: int = 34) -> dict:
    tiles = list(range(1, 9)) + [0]                 # 0 = blank, solved order
    blank = 8
    last = -1
    for _ in range(scramble):
        r, c = divmod(blank, 3)
        moves = []
        if r > 0: moves.append(blank - 3)
        if r < 2: moves.append(blank + 3)
        if c > 0: moves.append(blank - 1)
        if c < 2: moves.append(blank + 1)
        moves = [m for m in moves if m != last]
        m = rng.choice(moves)
        tiles[blank], tiles[m] = tiles[m], tiles[blank]
        last, blank = blank, m
    if tiles == list(range(1, 9)) + [0]:            # freak case: rescramble once
        return gen_sliding(rng, scramble + 7)
    return {"tiles": tiles}


def check_sliding(data: dict, moves: list) -> bool:
    tiles = data["tiles"][:]
    blank = tiles.index(0)
    if not isinstance(moves, list) or len(moves) > 400:
        return False
    for m in moves:
        if not isinstance(m, int) or not 0 <= m < 9:
            return False
        r1, c1 = divmod(blank, 3)
        r2, c2 = divmod(m, 3)
        if abs(r1 - r2) + abs(c1 - c2) != 1:
            return False
        tiles[blank], tiles[m] = tiles[m], tiles[blank]
        blank = m
    return tiles == list(range(1, 9)) + [0]


# ── lights out ───────────────────────────────────────────────────────────────
def _toggle(grid: list, i: int, w: int, h: int):
    r, c = divmod(i, w)
    for rr, cc in ((r, c), (r - 1, c), (r + 1, c), (r, c - 1), (r, c + 1)):
        if 0 <= rr < h and 0 <= cc < w:
            grid[rr * w + cc] ^= 1


def gen_lightsout(rng: random.Random, w: int = 4, h: int = 4) -> dict:
    grid = [0] * (w * h)
    presses = rng.sample(range(w * h), rng.randint(5, 7))
    for i in presses:
        _toggle(grid, i, w, h)
    if not any(grid):
        grid[rng.randrange(w * h)] ^= 1             # never start solved
    return {"grid": grid, "w": w, "h": h}


def check_lightsout(data: dict, presses: list) -> bool:
    if not isinstance(presses, list) or len(presses) > 200:
        return False
    grid = data["grid"][:]
    w, h = data["w"], data["h"]
    for i in presses:
        if not isinstance(i, int) or not 0 <= i < w * h:
            return False
        _toggle(grid, i, w, h)
    return not any(grid)


# ── tetromino fill ───────────────────────────────────────────────────────────
# the 7 tetrominoes as offset sets; rotations computed on the fly
TETROMINOES = {
    "I": [(0, 0), (1, 0), (2, 0), (3, 0)],
    "O": [(0, 0), (1, 0), (0, 1), (1, 1)],
    "T": [(0, 0), (1, 0), (2, 0), (1, 1)],
    "S": [(1, 0), (2, 0), (0, 1), (1, 1)],
    "Z": [(0, 0), (1, 0), (1, 1), (2, 1)],
    "L": [(0, 0), (0, 1), (0, 2), (1, 2)],
    "J": [(1, 0), (1, 1), (1, 2), (0, 2)],
}


def _normalize(cells) -> tuple:
    xs = min(x for x, y in cells)
    ys = min(y for x, y in cells)
    return tuple(sorted((x - xs, y - ys) for x, y in cells))


def _rotations(shape) -> list[tuple]:
    out, cur = [], list(shape)
    for _ in range(4):
        cur = [(y, -x) for x, y in cur]
        n = _normalize(cur)
        if n not in out:
            out.append(n)
    return out

ROTATIONS = {name: _rotations(shape) for name, shape in TETROMINOES.items()}
ALL_FORMS = {form for forms in ROTATIONS.values() for form in forms}


def gen_tetromino(rng: random.Random, w: int = 5, h: int = 4) -> dict:
    """Tile the w×h region with tetrominoes by backtracking, then hand the
    player the piece list (shuffled) and an empty region."""
    grid = [-1] * (w * h)
    pieces: list[str] = []

    def fit(form, x0, y0):
        cells = []
        for dx, dy in form:
            x, y = x0 + dx, y0 + dy
            if not (0 <= x < w and 0 <= y < h) or grid[y * w + x] != -1:
                return None
            cells.append((x, y))
        return cells

    def solve() -> bool:
        try:
            i = grid.index(-1)
        except ValueError:
            return True
        y0, x0 = divmod(i, w)
        names = list(ROTATIONS)
        rng.shuffle(names)
        for name in names:
            for form in ROTATIONS[name]:
                # anchor so the form's first empty-covering cell lands on (x0,y0)
                for ax, ay in form:
                    cells = fit([(dx - ax, dy - ay) for dx, dy in form], x0, y0)
                    if cells:
                        idx = len(pieces)
                        for x, y in cells:
                            grid[y * w + x] = idx
                        pieces.append(name)
                        if solve():
                            return True
                        for x, y in cells:
                            grid[y * w + x] = -1
                        pieces.pop()
        return False

    solve()
    shown = pieces[:]
    rng.shuffle(shown)
    return {"w": w, "h": h, "pieces": shown,
            "shapes": {n: [list(c) for c in ROTATIONS[n][0]] for n in set(shown)}}


def check_tetromino(data: dict, assignment: list) -> bool:
    """assignment: per-cell piece index (0..n-1), row-major, every cell filled."""
    w, h, pieces = data["w"], data["h"], data["pieces"]
    if not isinstance(assignment, list) or len(assignment) != w * h:
        return False
    groups: dict[int, list] = {}
    for i, v in enumerate(assignment):
        if not isinstance(v, int) or not 0 <= v < len(pieces):
            return False
        groups.setdefault(v, []).append((i % w, i // w))
    if len(groups) != len(pieces):
        return False
    for idx, cells in groups.items():
        if len(cells) != 4:
            return False
        if _normalize(cells) not in ROTATIONS[pieces[idx]]:
            return False
    return True


# ── dealing & checking ───────────────────────────────────────────────────────
INTERACTIVE = ("sliding", "lightsout", "tetromino")
_MC_WEIGHT = [("sequence", 3), ("riddle", 2)]
_GAME_WEIGHT = [("sliding", 3), ("lightsout", 3), ("tetromino", 3)] + _MC_WEIGHT


def deal(rng: random.Random, used_riddles: set[int]) -> dict:
    """Returns {"kind", "limit", and either question fields or minigame data}."""
    pool = [k for k, wt in _GAME_WEIGHT for _ in range(wt)]
    kind = rng.choice(pool)
    if kind == "riddle":
        fresh = [i for i in range(len(RIDDLES)) if i not in used_riddles]
        if not fresh:
            kind = "sequence"
        else:
            idx = rng.choice(fresh)
            used_riddles.add(idx)
            r = RIDDLES[idx]
            options = r["options"][:]
            rng.shuffle(options)
            return {"kind": "riddle", "limit": TIME_LIMITS["riddle"],
                    "text": r["text"], "options": options,
                    "correct": options.index(r["correct"])}
    if kind == "sequence":
        q = gen_sequence(rng)
        q.update({"kind": "sequence", "limit": TIME_LIMITS["sequence"]})
        return q
    gen = {"sliding": gen_sliding, "lightsout": gen_lightsout,
           "tetromino": gen_tetromino}[kind]
    data = gen(rng)
    data.update({"kind": kind, "limit": TIME_LIMITS[kind]})
    return data


def check(kind: str, data: dict, payload) -> bool:
    if kind == "sliding":
        return check_sliding(data, payload)
    if kind == "lightsout":
        return check_lightsout(data, payload)
    if kind == "tetromino":
        return check_tetromino(data, payload)
    return False
