"""
Puzzle isles — failable, time-limited brain challenges.

Five interactive/generated kinds (client never receives fields in "secret"):

  · tetromino  Talos-Principle-style sigil fill: drag the given pieces to
               tile a 4×4 region exactly. NO rotation — each piece comes in
               the orientation it must be placed. Generated by tiling the
               region first, so always solvable.
  · nonogram   5×5 picross against a 30s clock: paint cells to satisfy
               row/column clues. Half the solution comes pre-filled
               ("given" cells, locked in the client). Any grid matching
               the clues counts.
  · simon      memory: watch a flashed sequence (starts at 6 tones) on a
               3×3 pad, then reproduce it.
  · anagram    unscramble a themed word (typed answer).
  · ravens     Raven's-matrix: 3×3 glyph grid follows hidden row/col rules;
               pick the missing ninth tile.

Plus "riddle" — ★ PLACEHOLDER hand-written brain teasers at low weight.
Replace with your own; good sources: Project Gutenberg (Sam Loyd, Dudeney —
public domain), Martin Gardner / Smullyan collections, Puzzling StackExchange
(CC BY-SA), MindYourDecisions, NPR Sunday Puzzle, Mensa/GCHQ puzzle books.
Riddle format: {"text", "options" (4), "correct" (one of options)}.
"""
from __future__ import annotations

import random

# time limit (seconds) per kind — the server enforces these.
# Simon has NO clock: one wrong tap is the failure, not the seconds.
TIME_LIMITS = {"riddle": 30, "tetromino": 45, "nonogram": 30,
               "simon": None, "anagram": 30, "ravens": 30}

INTERACTIVE = ("tetromino", "nonogram", "simon", "anagram", "ravens")

# ── canned riddles (PLACEHOLDERS — swap in your own set) ─────────────────────
RIDDLES: list[dict] = [
    {"text": "I am taken from a mine and shut in a wooden case, from which I am "
             "never released — yet almost everyone uses me. What am I?",
     "options": ["Pencil lead", "A diamond", "Coal", "A nail"],
     "correct": "Pencil lead"},
    {"text": "A farmer must ferry a wolf, a goat, and a cabbage across a river. The "
             "boat holds the farmer and one item. Unattended, wolf eats goat, goat "
             "eats cabbage. Minimum crossings?",
     "options": ["7", "5", "9", "11"], "correct": "7"},
    {"text": "Two guards, two doors: one door frees you, one dooms you; one guard "
             "always lies, one always tells the truth. One question to find freedom?",
     "options": [
         "Ask either: “Which door would the other guard call safe?” — take the opposite",
         "Ask either: “Are you the liar?” — trust whoever says no",
         "Ask either: “Which door is safe?” — take the door indicated",
         "No single question can settle it"],
     "correct": "Ask either: “Which door would the other guard call safe?” — take the opposite"},
    {"text": "A snail climbs a 10 m well: up 3 m by day, back 2 m by night. "
             "On which day does it get out?",
     "options": ["Day 8", "Day 10", "Day 7", "Day 9"], "correct": "Day 8"},
    {"text": "A cube painted red is cut into 27 equal cubes. How many small cubes "
             "have exactly two painted faces?",
     "options": ["12", "8", "6", "9"], "correct": "12"},
    {"text": "Using 3, 3, 8, 8 each exactly once with + − × ÷ and parentheses, "
             "which expression makes 24?",
     "options": ["8 ÷ (3 − 8 ÷ 3)", "(8 + 8) × 3 ÷ 3", "3 × 8 + 3 − 8", "(3 + 3) × 8 ÷ 8"],
     "correct": "8 ÷ (3 − 8 ÷ 3)"},
]

# ── anagram wordlist (mythology / seafaring / worldly — 6-9 letters) ─────────
WORDS = [
    "ODYSSEY", "TRIREME", "ORACLE", "OLYMPUS", "LABYRINTH", "MINOTAUR",
    "PEGASUS", "TITANS", "AEGEAN", "HELMSMAN", "COMPASS", "LANTERN",
    "HARBOR", "ANCHOR", "VOYAGE", "ISLAND", "TEMPEST", "SIRENS",
    "GOLDEN", "FLEECE", "ARGONAUT", "CENTAUR", "GRIFFIN", "PHOENIX",
    "MARBLE", "COLUMN", "TEMPLE", "SCROLLS", "RIDDLES", "SPHINX",
    "CYCLOPS", "HYDRA", "KRAKEN", "POSEIDON", "ATHENA", "HERMES",
    "APOLLO", "ARTEMIS", "DOLPHIN", "OCTOPUS", "SEAWEED", "CORAL",
    "PIRATE", "PLUNDER", "TREASURE", "RELIC", "AMPHORA", "CHARIOT",
    "JAVELIN", "STADIUM", "LAUREL", "OLIVES", "GRAPES", "HONEY",
    "THUNDER", "TRIDENT", "SANDALS", "HELMET", "GALLEY", "RUDDER",
]
_WORD_SET = set(WORDS)


# ── tetromino sigil fill (Talos-Principle style) ─────────────────────────────
TETROMINOES = {
    "I": [(0, 0), (1, 0), (2, 0), (3, 0)],
    "O": [(0, 0), (1, 0), (0, 1), (1, 1)],
    "T": [(0, 0), (1, 0), (2, 0), (1, 1)],
    "S": [(1, 0), (2, 0), (0, 1), (1, 1)],
    "Z": [(0, 0), (1, 0), (1, 1), (2, 1)],
    "L": [(0, 0), (0, 1), (0, 2), (1, 2)],
    "J": [(1, 0), (1, 1), (1, 2), (0, 2)],
}


def _normalize(cells) -> tuple:
    xs = min(x for x, y in cells)
    ys = min(y for x, y in cells)
    return tuple(sorted((x - xs, y - ys) for x, y in cells))


def _rotations(shape) -> list[tuple]:
    out, cur = [], list(shape)
    for _ in range(4):
        cur = [(y, -x) for x, y in cur]
        n = _normalize(cur)
        if n not in out:
            out.append(n)
    return out

ROTATIONS = {name: _rotations(shape) for name, shape in TETROMINOES.items()}


def gen_tetromino(rng: random.Random, w: int = 4, h: int = 4) -> dict:
    """Tile the region (rotations allowed while GENERATING), then hand each
    piece to the player in exactly the orientation it was placed."""
    grid = [-1] * (w * h)
    forms: list[tuple] = []                 # normalized form of each placed piece

    def fit(form, x0, y0):
        cells = []
        for dx, dy in form:
            x, y = x0 + dx, y0 + dy
            if not (0 <= x < w and 0 <= y < h) or grid[y * w + x] != -1:
                return None
            cells.append((x, y))
        return cells

    def solve() -> bool:
        try:
            i = grid.index(-1)
        except ValueError:
            return True
        y0, x0 = divmod(i, w)
        names = list(ROTATIONS)
        rng.shuffle(names)
        for name in names:
            for form in ROTATIONS[name]:
                for ax, ay in form:
                    cells = fit([(dx - ax, dy - ay) for dx, dy in form], x0, y0)
                    if cells:
                        idx = len(forms)
                        for x, y in cells:
                            grid[y * w + x] = idx
                        forms.append(_normalize(cells))
                        if solve():
                            return True
                        for x, y in cells:
                            grid[y * w + x] = -1
                        forms.pop()
        return False

    solve()
    order = list(range(len(forms)))
    rng.shuffle(order)
    pieces = [[list(c) for c in forms[i]] for i in order]
    return {"w": w, "h": h, "pieces": pieces, "secret": {}}


def check_tetromino(data: dict, assignment) -> bool:
    w, h, pieces = data["w"], data["h"], data["pieces"]
    if not isinstance(assignment, list) or len(assignment) != w * h:
        return False
    groups: dict[int, list] = {}
    for i, v in enumerate(assignment):
        if not isinstance(v, int) or not 0 <= v < len(pieces):
            return False
        groups.setdefault(v, []).append((i % w, i // w))
    if len(groups) != len(pieces):
        return False
    for idx, cells in groups.items():
        want = tuple(sorted(tuple(c) for c in pieces[idx]))
        if len(cells) != 4 or _normalize(cells) != want:
            return False
    return True


# ── nonogram (picross 5×5) ───────────────────────────────────────────────────
def _clues(line) -> list[int]:
    out, run = [], 0
    for v in line:
        if v:
            run += 1
        elif run:
            out.append(run)
            run = 0
    if run:
        out.append(run)
    return out or [0]


def gen_nonogram(rng: random.Random, n: int = 5) -> dict:
    while True:
        grid = [1 if rng.random() < 0.55 else 0 for _ in range(n * n)]
        filled = sum(grid)
        if n + 2 <= filled <= n * n - 3:            # not trivial, not full
            break
    rows = [_clues(grid[r * n:(r + 1) * n]) for r in range(n)]
    cols = [_clues(grid[c::n]) for c in range(n)]
    # head start for the short clock: half the solution comes pre-painted
    filled_idx = [i for i, v in enumerate(grid) if v]
    given = sorted(rng.sample(filled_idx, len(filled_idx) // 2))
    return {"n": n, "rows": rows, "cols": cols, "given": given, "secret": {}}


def check_nonogram(data: dict, grid) -> bool:
    n = data["n"]
    if not isinstance(grid, list) or len(grid) != n * n:
        return False
    if any(v not in (0, 1) for v in grid):
        return False
    rows = [_clues(grid[r * n:(r + 1) * n]) for r in range(n)]
    cols = [_clues(grid[c::n]) for c in range(n)]
    return rows == data["rows"] and cols == data["cols"]


# ── simon (memory sequence, starts at 6) ─────────────────────────────────────
def gen_simon(rng: random.Random, length: int = 6) -> dict:
    seq = []
    for _ in range(length):
        nxt = rng.randrange(9)
        while seq and nxt == seq[-1]:               # no immediate repeats
            nxt = rng.randrange(9)
        seq.append(nxt)
    # the sequence must be public — the client has to flash it
    return {"pad": 9, "seq": seq, "secret": {}}


def check_simon(data: dict, taps) -> bool:
    return isinstance(taps, list) and taps == data["seq"]


# ── anagram unscramble ───────────────────────────────────────────────────────
def gen_anagram(rng: random.Random) -> dict:
    word = rng.choice(WORDS)
    letters = list(word)
    for _ in range(20):
        rng.shuffle(letters)
        if "".join(letters) != word:
            break
    return {"letters": "".join(letters), "length": len(word),
            "secret": {"word": word}}


def check_anagram(data: dict, guess) -> bool:
    if not isinstance(guess, str):
        return False
    guess = guess.strip().upper()
    word = data["secret"]["word"]
    if guess == word:
        return True
    # any real word from our list using exactly these letters also counts
    return sorted(guess) == sorted(word) and guess in _WORD_SET


# ── raven's matrix ───────────────────────────────────────────────────────────
_SHAPES = ["circle", "square", "triangle", "diamond"]
_FILLS = ["empty", "half", "full"]


def _rule(rng: random.Random, values: list):
    """Returns f(row, col) -> value; one of three systematic rules."""
    vals = values[:]
    rng.shuffle(vals)
    vals = vals[:3]
    mode = rng.choice(["row", "col", "latin"])
    if mode == "row":
        return lambda r, c: vals[r]
    if mode == "col":
        return lambda r, c: vals[c]
    return lambda r, c: vals[(r + c) % 3]


def gen_ravens(rng: random.Random) -> dict:
    shape_of = _rule(rng, _SHAPES)
    count_of = _rule(rng, [1, 2, 3])
    fill_of = _rule(rng, _FILLS)
    glyph = lambda r, c: {"shape": shape_of(r, c), "count": count_of(r, c),
                          "fill": fill_of(r, c)}
    grid = [glyph(r, c) for r in range(3) for c in range(3)]
    answer = grid[8]
    shown = grid[:8]

    def mutate(g):
        m = dict(g)
        attr = rng.choice(["shape", "count", "fill"])
        if attr == "shape":
            m["shape"] = rng.choice([s for s in _SHAPES if s != g["shape"]])
        elif attr == "count":
            m["count"] = rng.choice([n for n in (1, 2, 3, 4) if n != g["count"]])
        else:
            m["fill"] = rng.choice([f for f in _FILLS if f != g["fill"]])
        return m

    options = [answer]
    guard = 0
    while len(options) < 4 and guard < 200:
        guard += 1
        cand = mutate(answer)
        if rng.random() < 0.4:
            cand = mutate(cand)
        if cand not in options:
            options.append(cand)
    rng.shuffle(options)
    return {"grid": shown, "options": options,
            "secret": {"correct": options.index(answer)}}


def check_ravens(data: dict, idx) -> bool:
    return isinstance(idx, int) and idx == data["secret"]["correct"]


# ── dealing & checking ───────────────────────────────────────────────────────
_WEIGHTS = [("tetromino", 3), ("nonogram", 3), ("simon", 3),
            ("anagram", 3), ("ravens", 3), ("riddle", 1)]
_GENERATORS = {"tetromino": gen_tetromino, "nonogram": gen_nonogram,
               "simon": gen_simon, "anagram": gen_anagram, "ravens": gen_ravens}
_CHECKERS = {"tetromino": check_tetromino, "nonogram": check_nonogram,
             "simon": check_simon, "anagram": check_anagram, "ravens": check_ravens}


def deal(rng: random.Random, used_riddles: set[int]) -> dict:
    pool = [k for k, wt in _WEIGHTS for _ in range(wt)]
    kind = rng.choice(pool)
    if kind == "riddle":
        fresh = [i for i in range(len(RIDDLES)) if i not in used_riddles]
        if not fresh:
            kind = rng.choice(list(_GENERATORS))
        else:
            idx = rng.choice(fresh)
            used_riddles.add(idx)
            r = RIDDLES[idx]
            options = r["options"][:]
            rng.shuffle(options)
            return {"kind": "riddle", "limit": TIME_LIMITS["riddle"],
                    "text": r["text"], "options": options,
                    "correct": options.index(r["correct"])}
    data = _GENERATORS[kind](rng)
    data.update({"kind": kind, "limit": TIME_LIMITS[kind]})
    return data


def check(kind: str, data: dict, payload) -> bool:
    fn = _CHECKERS.get(kind)
    return bool(fn and fn(data, payload))
